### ISSUE TITLE
Feature Request: Set Audio Delay Based on Refresh Rate

### ISSUE THREAD

**Issue by Jdiesel87** [alexmarsev/sanear#11]
It would be very nice to have the ability to set rules for audio delay based on the display refresh rate. Many displays apply additional processing at 24hz which can cause the audio sync to be out by a considerable amount, 120ms in my case, whereas the audio sync does not exist when the display operates at 60hz. Some players have included the ability to do this but it would be nice to be able to achieve this independent of the player and have the render take care of the audio delay.

**Comment by alexmarsev** [comment]
It's in my design philosophy that audio renderer must have nothing to do with graphical stack directly - rates, presentation, etc. That is the field of video renderer. Thus not going to happen, sorry.
