### ISSUE TITLE
Option to enable timestretching or set rate of audio endpoint

### ISSUE THREAD

**Issue by zachsaw** [alexmarsev/sanear#8]
IIRC MPC Audio Renderer doesn't do timestretching so it asks the audio endpoint to output at a specific rate. If the hardware doesn't support it, you won't get any output.

This may or may not be better depending on the timestretching DSP used vs the audio hardware implementation (the audio hardware may very well just change its internal clock) so I'd prefer if Sanear gives you the option (accessible via COM interface) to select timestretching or directly setting the rate on the audio endpoint.

**Comment by alexmarsev** [comment]
I don't know of single dac that can do that through wasapi.

About sample rate conversion vs timestretching, I summed in up in https://github.com/alexmarsev/sanear/issues/7#issuecomment-127559415

I don't want to add options where I know for sure what is better, sorry.
